# Model Parameters
model_params: {
    model_config: {
        name: "GaussianModel",
        kwargs: {}
    },
    sh_degree: 1,
    # source_path: "data/mill19/rubble-pixsfm/train",
    source_path: "/mnt/hdd/data/Okutama_Action/GS_data/Scenario2/undistorted",  # adjust it to your own dataset
    partition_name: "okutama_s2_c4",
    pretrain_path: "output/okutama_s2_coarse/point_cloud/iteration_30000",
    model_path: "",
    images: "images",
    block_dim: [2, 1, 2],
    # aabb: 
    ssim_threshold: 0.12,
    resolution: -1,
    white_background: False,
    data_device: "cuda",
    eval: False,
}

# Pipeline Parameters
pipeline_params: {
    convert_SHs_python:  False,
    compute_cov3D_python:  False,
    debug:  False
}


# Optimization Parameters
optim_params: {
    iterations: 30_000,
    position_lr_init: 0.000064,
    position_lr_final: 0.00000064,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 30_000,
    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.004,
    rotation_lr: 0.001,
    percent_dense: 0.01,
    lambda_dssim: 0.2,
    densification_interval: 100,
    opacity_reset_interval: 3000,
    densify_from_iter: 500,
    densify_until_iter: 15_000,
    densify_grad_threshold: 0.0002
}


